/*
 * MyLand2.java
 *
 * Created on 2008年9月10日, 下午1:07
 */

package com.Exam.Index;

import javax.swing.*;
import com.Exam.bean.*;
import com.Exam.controller.ControllerFrame;
import com.Exam.dao.*;

/**
 *
 * @author  Administrator
 */
public class MyLand extends javax.swing.JFrame {

    /** Creates new form MyLand2 */
    public MyLand() {
    	this.setVisible(true);
    	this.setLocation(400, 300);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jpanel = new MyJPanel();
        choicejLabel = new javax.swing.JLabel();
        userChoicejComboBox = new javax.swing.JComboBox();
        choicejLabel1 = new javax.swing.JLabel();
        UserNameTextField = new javax.swing.JTextField();
        choicejLabel2 = new javax.swing.JLabel();
        PassWordjTextField = new javax.swing.JPasswordField();
        enterButton = new javax.swing.JButton();
        resButtonjButton = new javax.swing.JButton();

        jTextField3.setText("jTextField3");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        choicejLabel.setText("选择用户：");

        userChoicejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {  "","考生", "管理员" }));
        setTitle("海口联合农村商业银行业务知识及技能考试系统");
        choicejLabel1.setText("用户号：");

        UserNameTextField.setText("");

        choicejLabel2.setText(" 密  码 ：");

        PassWordjTextField.setText("");

        enterButton.setText("登录");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	enterButtonActionPerformed(evt);
            }
        });

        resButtonjButton.setText("重置");
        resButtonjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
               }
        });
        javax.swing.GroupLayout jpanelLayout = new javax.swing.GroupLayout(jpanel);
        jpanel.setLayout(jpanelLayout);
        jpanelLayout.setHorizontalGroup(
            jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelLayout.createSequentialGroup()
                .addGap(215, 381, 381)
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelLayout.createSequentialGroup()
                        .addComponent(choicejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userChoicejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(choicejLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PassWordjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                            .addGroup(jpanelLayout.createSequentialGroup()
                                .addComponent(choicejLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UserNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))))
                .addGap(82, 82, 82))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelLayout.createSequentialGroup()
                .addContainerGap(247, Short.MAX_VALUE)
                .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resButtonjButton)
                .addGap(123, 123, 123))
        );
        jpanelLayout.setVerticalGroup(
            jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelLayout.createSequentialGroup()
                .addGap(85, 181, 181)
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choicejLabel)
                    .addComponent(userChoicejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(choicejLabel1)
                    .addComponent(UserNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(choicejLabel2)
                    .addComponent(PassWordjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resButtonjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pack();
    }

private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {
	if(userChoicejComboBox.getSelectedIndex()==0){
		JOptionPane.showMessageDialog(this, "没有确定路径的'用户类型'", 
				"信息对话框",JOptionPane.WARNING_MESSAGE);
		return;
	}
	if(UserNameTextField.getText().equals("")){
		JOptionPane.showMessageDialog(this, "用户号不能为空",
				"密码不能为空",JOptionPane.WARNING_MESSAGE);
		return;
	}
	if(PassWordjTextField.getText().equals("")){
		JOptionPane.showMessageDialog(this,"密码不能为空","信息对话框",JOptionPane.WARNING_MESSAGE);
		return;
	}
	MyFindUserDao findUser = new MyFindUserDao();
	User user = new User();
	user.setUserName(UserNameTextField.getText());
//	user.setId(Integer.parseInt(UserNameTextField.getText().trim()));
	user.setPassWord(PassWordjTextField.getText());	
	
	System.out.println("user.getId()"+user.getId()+ " user.getPassWord()"+user.getPassWord());
	
	User users = findUser.getUser(user);
	System.out.println("user.getId()"+user.getId()+ " user.getUserType()"+user.getUserType());
	
	
	
	if((users.getUserType() == 1 && !(userChoicejComboBox.getSelectedItem().equals("管理员")))){
		System.out.println("user.getId()"+user.getId()+"user.getUserType()"+user.getUserType());
		JOptionPane.showMessageDialog(this,"登录系统身份不符","信息对话框",JOptionPane.WARNING_MESSAGE);
		return;
	}
	if((users.getUserType() == 0) && !(userChoicejComboBox.getSelectedItem().equals("考生"))){
		JOptionPane.showMessageDialog(this,"登录系统身份不符","信息对话框",JOptionPane.WARNING_MESSAGE);
		return;
	}
	if((users.getId()!= 0 )&&(users.getUserType()==0)){	    //学生界面控制
		int id = users.getId();
		java.io.File file = new java.io.File("save.txt");
		try {		
			if(file.exists()){
				file.delete();
			}
			file.createNewFile();
			java.io.FileOutputStream out = new java.io.FileOutputStream(file);	
			byte buy[] = (""+id).getBytes();	
			out.write(buy);								
			out.close();						
		} catch (Exception e) {					
			e.printStackTrace();					
		}
		InsertUserDao insertUserDao = new InsertUserDao();
		insertUserDao.setUserHaveIn(users);
		StudentExam studentExam = new StudentExam();		
		studentExam.setVisible(true);
		studentExam.setBounds(200, 200, 1024, 450);
		studentExam.setTitle("海口联合农村商业银行业务知识及技能考试系统");
		this.dispose();
	}
	if((users.getId()!=0)&&(users.getUserType()==1)){      //管理员界面控制
		dispose();
		ControllerFrame controller = new ControllerFrame();
		controller.setVisible(true);
		controller.setBounds(100,100, 700, 500);
	}
	else if(users.getId() == 0){
		JOptionPane.showMessageDialog(this,"用户名或密码错误","信息对话框",JOptionPane.WARNING_MESSAGE);
	}
}

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
	UserNameTextField.setText("");
	PassWordjTextField.setText("");	
}
public static void main(String[] args) {
	MyLand myLand = new MyLand();
	myLand.setVisible(true);
}
    
    private javax.swing.JLabel choicejLabel;
    private javax.swing.JLabel choicejLabel1;
    private javax.swing.JLabel choicejLabel2;
    private javax.swing.JButton enterButton;
    private javax.swing.JButton resButtonjButton;
    private javax.swing.JComboBox userChoicejComboBox;
    private javax.swing.JPasswordField PassWordjTextField;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField UserNameTextField;
    private javax.swing.JTextField jTextField3;
    private MyJPanel jpanel;
}
