/*
 * StudentExam.java
 *
 * Created on 2008年8月2日, 上午10:04
 */
package com.Exam.Index;

import javax.swing.JOptionPane;

import com.Exam.bean.*;
import com.Exam.dao.*;
import com.Exam.student.ExamPage;
import com.Exam.student.SkillExamPage;

/**
 *
 * @author  Administrator
 */
public class StudentExam extends javax.swing.JFrame {
    /** Creates new form StudentExam */
    public StudentExam() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	jPanel = new MySudentExamJPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        FilejMenu = new javax.swing.JMenu();
        openjMenuItem = new javax.swing.JMenuItem();
        closeMenuItem = new javax.swing.JMenuItem();
        watchjMenu = new javax.swing.JMenu();
        sleanjMenuItem = new javax.swing.JMenuItem();
        amendpassjMenuItem = new javax.swing.JMenuItem();
        aboutjMenu = new javax.swing.JMenu();
        aboutExamMenuItem = new javax.swing.JMenuItem();
        /*技能考试模块*/
        skilljMenu = new javax.swing.JMenu();
        skillExamMenuItem = new javax.swing.JMenuItem();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        FilejMenu.setText("业务知识考试");
        setTitle("海口联合农村商业银行业务知识及技能考试系统");
        openjMenuItem.setText("开始考试");
        openjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openjMenuItemActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        FilejMenu.add(openjMenuItem);

        closeMenuItem.setText("退出");
        closeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeMenuItemActionPerformed(evt);
            }
        });
        FilejMenu.add(closeMenuItem);

        jMenuBar1.add(FilejMenu);

        watchjMenu.setText("查看");

        sleanjMenuItem.setText("业务考试查分");
        sleanjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sleanjMenuItemActionPerformed(evt);
            }
        });
        watchjMenu.add(sleanjMenuItem);

        amendpassjMenuItem.setText("修改密码");
        amendpassjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amendpassjMenuItemActionPerformed(evt);
            }
        });
        watchjMenu.add(amendpassjMenuItem);

        jMenuBar1.add(watchjMenu);

        aboutjMenu.setText("关于");

        aboutExamMenuItem.setText("本次业务知识考试");
        aboutExamMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutExamMenuItemActionPerformed(evt);
            }
        });
        aboutjMenu.add(aboutExamMenuItem);

        jMenuBar1.add(aboutjMenu);
        
        /*
         * 技能考试模块
         */
        
        skilljMenu.setText("技能考试");

        skillExamMenuItem.setText("技能");
        skillExamMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	skillExamMenuItemActionPerformed(evt);
            }
        });
        skilljMenu.add(skillExamMenuItem);

        jMenuBar1.add(skilljMenu);
        

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
        pack();
    }

private void openjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
	java.io.File file = new java.io.File("save.txt");
	try{
		java.io.FileInputStream in = new java.io.FileInputStream(file);		
		byte byt[] = new byte[1024];					
		int len = in.read(byt);						
		String strid = new String(byt,0,len);	
		int id = Integer.parseInt(strid);
		MyFindUserDao findUser = new MyFindUserDao();
		User user = new User();
		user.setId(id);		
		User use = findUser.getUserID(user);		
		if((use.getHaveIn() != 1 && use.getHaveIn() != 21) || use.getFlag().equals("0") ){
			System.out.println("开始业务考试 ");
			ExamPage exampage = new ExamPage();
			exampage.setVisible(true);
			InsertUserDao insertUser = new InsertUserDao();
			
			if (use.getHaveIn() ==0)
			{
				use.setHaveIn(1);
			}
			else if (use.getHaveIn() ==20)
			{
				use.setHaveIn(21);
			}
			
			boolean b = insertUser.setUserHaveIn(use);			
		}
		else if(use.getHaveIn() == 1){
			JOptionPane.showMessageDialog(this, "你已经参加完业务知识考试了！", "信息对话框",JOptionPane.WARNING_MESSAGE);
		}
		in.close();									
	}catch (Exception e) {
		e.printStackTrace();							
	}
}
private void closeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
	int n = JOptionPane.showConfirmDialog(this, "确定要退出考试吗？", "确认对话框", JOptionPane.WARNING_MESSAGE);
	if(n == JOptionPane.YES_OPTION){
		System.exit(0);
	}
}
private void sleanjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
	java.io.File file = new java.io.File("save.txt");
	try{
		java.io.FileInputStream in = new java.io.FileInputStream(file);		
		byte byt[] = new byte[1024];					
		int len = in.read(byt);						
		String strid = new String(byt,0,len);	
		int id = Integer.parseInt(strid);
		FindGrade findGrade = new FindGrade();
		Grade grage = new Grade();
		grage.setId(id);
		System.out.println("hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh ");
		Grade gra = findGrade.getGradeID(grage);
		int radioMark = gra.getRadioResult();
		int fullMark = gra.getFullResule();
		int judgeMark = gra.getEsitResult();
		int bastMark = gra.getBatsisResult();
		int skillMark = gra.getSkillResult();
//		int sum = radioMark+fullMark+bastMark+skillMark;
		JOptionPane.showMessageDialog(this, "单选题得分："+radioMark+"\n"+
				"多选题得分："+fullMark+"\n"+"判断题得分："+judgeMark+"\n"+"技能得分："+skillMark+"\n"+
				"总分："+bastMark,"信息对话框", JOptionPane.WARNING_MESSAGE);
		in.close();									
	}catch (Exception e) {
		e.printStackTrace();							
	}	
}
private void amendpassjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
	dispose();
	MySetPassWord setPassWord  = new MySetPassWord();
	setPassWord.setVisible(true);
	setPassWord.setTitle("修改密码");
	setPassWord.setBounds(200, 200, 850, 350);
}	

private void aboutExamMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
	dispose();
	MyAbout myAbout = new MyAbout();
	myAbout.setVisible(true);
	myAbout.setTitle("关于业务知识考试");
	myAbout.setBounds(200, 200, 850, 350);
}  

/*技能模块*/

private void skillExamMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
	java.io.File file = new java.io.File("save.txt");
	try{
		java.io.FileInputStream in = new java.io.FileInputStream(file);		
		byte byt[] = new byte[1024];					
		int len = in.read(byt);						
		String strid = new String(byt,0,len);	
		int id = Integer.parseInt(strid);
		MyFindUserDao findUser = new MyFindUserDao();
		User user = new User();
		user.setId(id);		
		User use = findUser.getUserID(user);		
		if((use.getHaveIn() !=20 && use.getHaveIn() !=21) || use.getFlag().equals("0")){
			SkillExamPage exampage = new SkillExamPage();
			exampage.setVisible(true);
			InsertUserDao insertUser = new InsertUserDao();
			
			if (use.getHaveIn() ==0)
			{
				use.setHaveIn(20);
			}
			else if (use.getHaveIn() ==1)
			{
				use.setHaveIn(21);
			}
			boolean b = insertUser.setUserHaveIn(use);			
		}
		else if(use.getHaveIn() == 20){
			JOptionPane.showMessageDialog(this, "你已经参加完技能考试了！", "信息对话框",JOptionPane.WARNING_MESSAGE);
		}
		in.close();									
	}catch (Exception e) {
		e.printStackTrace();							
	}
	

}

    private javax.swing.JMenu FilejMenu;
    private javax.swing.JMenuItem aboutExamMenuItem;
    private javax.swing.JMenu aboutjMenu;
    private javax.swing.JMenuItem amendpassjMenuItem;
    private javax.swing.JMenuItem closeMenuItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem openjMenuItem;
    private javax.swing.JMenuItem sleanjMenuItem;
    private javax.swing.JMenu watchjMenu;
    private MySudentExamJPanel jPanel;
    /*技能考试模块*/
    private javax.swing.JMenuItem skillExamMenuItem;
    private javax.swing.JMenu skilljMenu;
}
